const data = [
    {
      "menuId": 171,
      "parentId": 0,
      "parentName": null,
      "name": "首页",
      "url": "main.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": -1,
      "open": null,
      "list": null
    },
    {
      "menuId": 256,
      "parentId": 234,
      "parentName": "区域服务商资金查询",
      "name": "导出",
      "url": null,
      "perms": "dailyFund:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 257,
      "parentId": 239,
      "parentName": "商城客户资金流水查询",
      "name": "查询",
      "url": null,
      "perms": "customerCapitalStream:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 258,
      "parentId": 239,
      "parentName": "商城客户资金流水查询",
      "name": "导出",
      "url": null,
      "perms": "customerCapitalStream:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 259,
      "parentId": 240,
      "parentName": "商城客户出入金查询",
      "name": "查询",
      "url": null,
      "perms": "customerInOutMoney:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 260,
      "parentId": 240,
      "parentName": "商城客户出入金查询",
      "name": "导出",
      "url": null,
      "perms": "customerInOutMoney:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 262,
      "parentId": 261,
      "parentName": "预付款券审核",
      "name": "查询",
      "url": null,
      "perms": "couponCheck:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 263,
      "parentId": 261,
      "parentName": "预付款券审核",
      "name": "审核",
      "url": null,
      "perms": "couponCheck:update,couponCheck:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 264,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "订货系统订单导出",
      "url": "modules/mallcustomer/orderSysReport.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 265,
      "parentId": 264,
      "parentName": "订货系统订单导出",
      "name": "导出",
      "url": null,
      "perms": "orderSysReport:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 269,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "商城客户充值记录查询",
      "url": "modules/ichannel/orderPaymentDTO.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 15,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "查看",
      "url": "",
      "perms": "sys:user:list,sys:user:info",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 16,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "新增",
      "url": "",
      "perms": "sys:user:save,sys:role:select",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 272,
      "parentId": 271,
      "parentName": "券流水查询",
      "name": "查询",
      "url": null,
      "perms": "couponsReport:couponAmountlog:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 17,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "修改",
      "url": "",
      "perms": "sys:user:update,sys:role:select",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 273,
      "parentId": 271,
      "parentName": "券流水查询",
      "name": "导出",
      "url": null,
      "perms": "couponsReport:couponAmountlog:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 18,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "删除",
      "url": "",
      "perms": "sys:user:delete",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 19,
      "parentId": 3,
      "parentName": "角色管理",
      "name": "查看",
      "url": "",
      "perms": "sys:role:list,sys:role:info",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 275,
      "parentId": 274,
      "parentName": "券对账查询",
      "name": "查询",
      "url": null,
      "perms": "couponsReport:couponCompareAccount:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 20,
      "parentId": 3,
      "parentName": "角色管理",
      "name": "新增",
      "url": "",
      "perms": "sys:role:save,sys:menu:list",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 276,
      "parentId": 274,
      "parentName": "券对账查询",
      "name": "导出",
      "url": null,
      "perms": "couponsReport:couponCompareAccount:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 21,
      "parentId": 3,
      "parentName": "角色管理",
      "name": "修改",
      "url": "",
      "perms": "sys:role:update,sys:menu:list",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 22,
      "parentId": 3,
      "parentName": "角色管理",
      "name": "删除",
      "url": "",
      "perms": "sys:role:delete",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 278,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "商城客户提现记录查询",
      "url": "modules/ichannel/withdrawOrderDTO.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 23,
      "parentId": 4,
      "parentName": "菜单管理",
      "name": "查看",
      "url": "",
      "perms": "sys:menu:list,sys:menu:info",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 279,
      "parentId": 269,
      "parentName": "商城客户充值记录查询",
      "name": "查询",
      "url": null,
      "perms": "orderPayment:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 24,
      "parentId": 4,
      "parentName": "菜单管理",
      "name": "新增",
      "url": "",
      "perms": "sys:menu:save,sys:menu:select",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 280,
      "parentId": 269,
      "parentName": "商城客户充值记录查询",
      "name": "导出",
      "url": null,
      "perms": "orderPayment:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 25,
      "parentId": 4,
      "parentName": "菜单管理",
      "name": "修改",
      "url": "",
      "perms": "sys:menu:update,sys:menu:select",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 281,
      "parentId": 278,
      "parentName": "商城客户提现记录查询",
      "name": "查询",
      "url": null,
      "perms": "withdrawOrder:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 26,
      "parentId": 4,
      "parentName": "菜单管理",
      "name": "删除",
      "url": "",
      "perms": "sys:menu:delete",
      "type": 2,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 282,
      "parentId": 278,
      "parentName": "商城客户提现记录查询",
      "name": "导出",
      "url": null,
      "perms": "withdrawOrder:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 284,
      "parentId": 283,
      "parentName": "券订单查询",
      "name": "查询",
      "url": null,
      "perms": "couponsReport:couponOrder:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 285,
      "parentId": 283,
      "parentName": "券订单查询",
      "name": "导出",
      "url": null,
      "perms": "couponsReport:couponOrder:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 286,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "订货分部货值增减",
      "url": "modules/dataMonitor/dealerBuyValue.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 287,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "订单货值增减",
      "url": "modules/dataMonitor/orderBuyValue.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 32,
      "parentId": 31,
      "parentName": "机构管理",
      "name": "机构列表",
      "url": "modules/org/organization.html",
      "perms": "",
      "type": 1,
      "icon": "fa fa-list",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 288,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "预定回购比",
      "url": "modules/dataMonitor/emptyRate.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 294,
      "parentId": 292,
      "parentName": "用户信息变更",
      "name": "用户手机号修改",
      "url": "modules/userinfo/ModificationPhoneNum.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 296,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "审批用户管理",
      "url": "modules/audit/sysUserAudit.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 297,
      "parentId": 296,
      "parentName": "审批用户管理",
      "name": "查询",
      "url": null,
      "perms": "sysUser:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 298,
      "parentId": 296,
      "parentName": "审批用户管理",
      "name": "确认",
      "url": null,
      "perms": "sysUser:update",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 300,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "申请订单查询",
      "url": "modules/audit/myAudit.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 301,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "历史订单查询",
      "url": "modules/audit/auditHistory.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 302,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "回购单审批管理",
      "url": "modules/audit/auditOrder.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 303,
      "parentId": 302,
      "parentName": "回购单审批管理",
      "name": "查询",
      "url": null,
      "perms": "auditOrder:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 304,
      "parentId": 302,
      "parentName": "回购单审批管理",
      "name": "提交",
      "url": null,
      "perms": "auditOrder:check",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 49,
      "parentId": 0,
      "parentName": null,
      "name": "工作日历",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-calendar",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 305,
      "parentId": 105,
      "parentName": "订单管理",
      "name": "全款订单查询",
      "url": "modules/audit/fullBill.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 306,
      "parentId": 294,
      "parentName": "用户手机号修改",
      "name": "查询",
      "url": null,
      "perms": "modificationPhoneNum:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 307,
      "parentId": 294,
      "parentName": "用户手机号修改",
      "name": "修改",
      "url": null,
      "perms": "modificationPhoneNum:update",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 308,
      "parentId": 300,
      "parentName": "申请订单查询",
      "name": "查询",
      "url": null,
      "perms": "myAudit:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 309,
      "parentId": 301,
      "parentName": "历史订单查询",
      "name": "查询",
      "url": null,
      "perms": "auditHistory:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 310,
      "parentId": 305,
      "parentName": "全款订单查询",
      "name": "查询",
      "url": null,
      "perms": "fullBill:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 313,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "审批操作管理",
      "url": "modules/audit/goldenBeanAudit.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 316,
      "parentId": 313,
      "parentName": "审批操作管理",
      "name": "查询",
      "url": null,
      "perms": "goldenBean:findlist",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 317,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "交易密码设置",
      "url": null,
      "perms": "sys:user:addOrUpdatePwd",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 318,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "添加审批",
      "url": "modules/audit/goldenBean.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 319,
      "parentId": 318,
      "parentName": "添加审批",
      "name": "提交申请",
      "url": null,
      "perms": "goldenBean:findUser",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 320,
      "parentId": 318,
      "parentName": "添加审批",
      "name": "确认",
      "url": null,
      "perms": "goldenBean:add",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 321,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "审批密码重置",
      "url": null,
      "perms": "sys:user:resetPwd",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 322,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "对公银行卡管理",
      "url": "modules/corporate/corporateBankCard.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 323,
      "parentId": 295,
      "parentName": "审批管理",
      "name": "对公提现审批",
      "url": "modules/corporate/withdrawalAndApproval.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 68,
      "parentId": 31,
      "parentName": "机构管理",
      "name": "会员信息",
      "url": "modules/org/bmDealer.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-vcard",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 324,
      "parentId": 323,
      "parentName": "对公提现审批",
      "name": "查询",
      "url": null,
      "perms": "corporate:audit:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 325,
      "parentId": 322,
      "parentName": "对公银行卡管理",
      "name": "查询",
      "url": null,
      "perms": "corporate:bankcard:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 326,
      "parentId": 322,
      "parentName": "对公银行卡管理",
      "name": "提现",
      "url": null,
      "perms": "corporate:withdrawal:apply",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 327,
      "parentId": 322,
      "parentName": "对公银行卡管理",
      "name": "绑卡",
      "url": null,
      "perms": "corporate:bankcard:bindcard",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 328,
      "parentId": 322,
      "parentName": "对公银行卡管理",
      "name": "解绑",
      "url": null,
      "perms": "corporate:bankcard:unbindcard",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 73,
      "parentId": 0,
      "parentName": null,
      "name": "金贝管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-btc",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 329,
      "parentId": 323,
      "parentName": "对公提现审批",
      "name": "提交审批",
      "url": null,
      "perms": "corporate:audit:approve",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 330,
      "parentId": 0,
      "parentName": null,
      "name": "商城运营信息查询",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 331,
      "parentId": 330,
      "parentName": "商城运营信息查询",
      "name": "运营信息查询",
      "url": "modules/mallrun/mallrun.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 332,
      "parentId": 331,
      "parentName": "运营信息查询",
      "name": "查询",
      "url": null,
      "perms": "mallRun:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 333,
      "parentId": 322,
      "parentName": "对公银行卡管理",
      "name": "查询机构",
      "url": null,
      "perms": "corporate:bankcard:getOrgIds",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 334,
      "parentId": 313,
      "parentName": "审批操作管理",
      "name": "审批",
      "url": null,
      "perms": "couponSurplus:addcoupon",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 335,
      "parentId": 313,
      "parentName": "审批操作管理",
      "name": "通过",
      "url": null,
      "perms": "couponSurplus:approval",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 336,
      "parentId": 313,
      "parentName": "审批操作管理",
      "name": "驳回",
      "url": null,
      "perms": "couponSurplus:approval",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 338,
      "parentId": 313,
      "parentName": "审批操作管理",
      "name": "驳回",
      "url": null,
      "perms": "goldenBean:approval",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 339,
      "parentId": 313,
      "parentName": "审批操作管理",
      "name": "通过",
      "url": null,
      "perms": "goldenBean:approval",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 340,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "用户参数修改记录查询",
      "url": "modules/userinfo/UserParamChangeRecord.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 341,
      "parentId": 340,
      "parentName": "用户参数修改记录查询",
      "name": "查询",
      "url": null,
      "perms": "userParamChangeRecord:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 342,
      "parentId": 340,
      "parentName": "用户参数修改记录查询",
      "name": "导出",
      "url": null,
      "perms": "userParamChangeRecord:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 343,
      "parentId": 331,
      "parentName": "运营信息查询",
      "name": "导出",
      "url": null,
      "perms": "mallRun:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 95,
      "parentId": 0,
      "parentName": null,
      "name": "交易信息",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-handshake-o ",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 96,
      "parentId": 95,
      "parentName": "交易信息",
      "name": "订单列表",
      "url": "modules/dataMonitor/bmTradeHoldBill.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-list-ol",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 97,
      "parentId": 0,
      "parentName": null,
      "name": "风控图表",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-area-chart ",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 98,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "客户资金变动趋势图",
      "url": "modules/org/dealerMoneyInfo.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-line-chart",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 99,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "订货分部单据趋势图",
      "url": "modules/org/dealerTradeInfo.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-line-chart",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 100,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "订货分部下单分布图",
      "url": "modules/dataMonitor/historyDistribution.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-line-chart",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 119,
      "parentId": 0,
      "parentName": null,
      "name": "商户信息",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-btc",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 125,
      "parentId": 0,
      "parentName": null,
      "name": "退差价管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-credit-card-alt",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 131,
      "parentId": 68,
      "parentName": "会员信息",
      "name": "查看",
      "url": null,
      "perms": "org:dealer:list,",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 132,
      "parentId": 32,
      "parentName": "机构列表",
      "name": "查看",
      "url": null,
      "perms": "org:bmorganization:list,org:bmorganization:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 133,
      "parentId": 119,
      "parentName": "商户信息",
      "name": "商品信息",
      "url": "modules/delivery/bmSymbolInfo.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 134,
      "parentId": 95,
      "parentName": "交易信息",
      "name": "资金流水信息",
      "url": "modules/dataMonitor/bmAmAmountlog.html",
      "perms": null,
      "type": 1,
      "icon": "fa-fa-list-ol",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 135,
      "parentId": 95,
      "parentName": "交易信息",
      "name": "备货商结算汇总",
      "url": "modules/dataMonitor/bmAmCount.html",
      "perms": null,
      "type": 1,
      "icon": "",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 136,
      "parentId": 135,
      "parentName": "备货商结算汇总",
      "name": "导出",
      "url": null,
      "perms": "amamountlog:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 137,
      "parentId": 134,
      "parentName": "资金流水信息",
      "name": "查看",
      "url": null,
      "perms": "amamountlog:list,amamountlog:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 138,
      "parentId": 135,
      "parentName": "备货商结算汇总",
      "name": "查看",
      "url": null,
      "perms": "amamountlog:count",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 139,
      "parentId": 31,
      "parentName": "机构管理",
      "name": "服务商信息",
      "url": "modules/org/facilitatorDealer.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-vcard",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 140,
      "parentId": 139,
      "parentName": "服务商信息",
      "name": "查看",
      "url": null,
      "perms": "org:dealer:facilitatorList,org:dealer:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 141,
      "parentId": 31,
      "parentName": "机构管理",
      "name": "订货分部信息",
      "url": "modules/org/orderDealer.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-vcard",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 142,
      "parentId": 141,
      "parentName": "订货分部信息",
      "name": "查看",
      "url": null,
      "perms": "org:dealer:orderList,org:dealer:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 143,
      "parentId": 133,
      "parentName": "商品信息",
      "name": "查看",
      "url": null,
      "perms": "bmsymbolinfo:list,bmsymbolinfo:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 144,
      "parentId": 95,
      "parentName": "交易信息",
      "name": "资产异动信息",
      "url": "modules/dataMonitor/dealerMoneyChange.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 145,
      "parentId": 144,
      "parentName": "资产异动信息",
      "name": "查看",
      "url": null,
      "perms": "amamountlog:dealerChange",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 147,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "订货分部备货金使用率监控",
      "url": "modules/dataMonitor/riskRatio.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 157,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "查看",
      "url": null,
      "perms": "sys:schedule:list,sys:schedule:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 158,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "新增",
      "url": null,
      "perms": "sys:schedule:save",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 159,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "修改",
      "url": null,
      "perms": "sys:schedule:update",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 160,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "删除",
      "url": null,
      "perms": "sys:schedule:delete",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 161,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "暂停",
      "url": null,
      "perms": "sys:schedule:pause",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 162,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "恢复",
      "url": null,
      "perms": "sys:schedule:resume",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 163,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "立即执行",
      "url": null,
      "perms": "sys:schedule:run",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 164,
      "parentId": 156,
      "parentName": "定时任务",
      "name": "日志列表",
      "url": null,
      "perms": "sys:schedule:log",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 165,
      "parentId": 135,
      "parentName": "备货商结算汇总",
      "name": "录入轧差",
      "url": null,
      "perms": "amamountlog:patchAmCloseProfits",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 166,
      "parentId": 148,
      "parentName": "退差价三审",
      "name": "审查",
      "url": null,
      "perms": "refundapply:commitApply:third",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 167,
      "parentId": 148,
      "parentName": "退差价三审",
      "name": "查看",
      "url": null,
      "perms": "refundapply:list,refundapply:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 168,
      "parentId": 120,
      "parentName": "退差价审核",
      "name": "审查",
      "url": null,
      "perms": "refundapply:commitApply:first",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 169,
      "parentId": 126,
      "parentName": "退差价复审",
      "name": "审查",
      "url": null,
      "perms": "refundapply:commitApply:second",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 172,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "创建机构账号",
      "url": null,
      "perms": "org:bmorganization:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 173,
      "parentId": 2,
      "parentName": "管理员列表",
      "name": "创建服务商账号",
      "url": null,
      "perms": "org:dealer:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 175,
      "parentId": 149,
      "parentName": "转移机构管理",
      "name": "上传名单",
      "url": null,
      "perms": "shiftorgrecord:import",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 176,
      "parentId": 149,
      "parentName": "转移机构管理",
      "name": "下载模板",
      "url": null,
      "perms": "shiftorgrecord:template:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 177,
      "parentId": 149,
      "parentName": "转移机构管理",
      "name": "审核",
      "url": null,
      "perms": "shiftorgrecord:verifyBatch",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 178,
      "parentId": 149,
      "parentName": "转移机构管理",
      "name": "导出",
      "url": null,
      "perms": "shiftorgrecord:downVerify",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 179,
      "parentId": 149,
      "parentName": "转移机构管理",
      "name": "查看",
      "url": null,
      "perms": "shiftorgrecord:verify:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 180,
      "parentId": 174,
      "parentName": "转移机构查询",
      "name": "查看",
      "url": null,
      "perms": "shiftorgrecord:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 181,
      "parentId": 174,
      "parentName": "转移机构查询",
      "name": "导出",
      "url": null,
      "perms": "shiftorgrecord:downRecord",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 183,
      "parentId": 0,
      "parentName": null,
      "name": "客户订单信息详情",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 184,
      "parentId": 183,
      "parentName": "客户订单信息详情",
      "name": "订单信息",
      "url": "modules/generator/ordersDetail.html",
      "perms": "orders:detail:new",
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 185,
      "parentId": 184,
      "parentName": "订单信息",
      "name": "查看",
      "url": null,
      "perms": "orders:detail:new",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 187,
      "parentId": 184,
      "parentName": "订单信息",
      "name": "导出",
      "url": null,
      "perms": "orders:detail:new:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 188,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "客户信息查询",
      "url": "modules/generator/clientInfoInquire.html",
      "perms": "dfmalluserinfo:userinfo:list",
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 189,
      "parentId": 188,
      "parentName": "客户信息查询",
      "name": "查询",
      "url": null,
      "perms": "org:dealer:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 190,
      "parentId": 188,
      "parentName": "客户信息查询",
      "name": "查看",
      "url": null,
      "perms": "dfmalluserinfo:userinfo:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 191,
      "parentId": 188,
      "parentName": "客户信息查询",
      "name": "查询机构",
      "url": null,
      "perms": "org:bmorganization:level:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 192,
      "parentId": 31,
      "parentName": "机构管理",
      "name": "机构信息查询",
      "url": "modules/org/orgInfoInquire.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 193,
      "parentId": 192,
      "parentName": "机构信息查询",
      "name": "查看",
      "url": null,
      "perms": "org:bmorganization:level:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 194,
      "parentId": 192,
      "parentName": "机构信息查询",
      "name": "获取会员",
      "url": null,
      "perms": "org:dealer:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 195,
      "parentId": 120,
      "parentName": "退差价审核",
      "name": "导出",
      "url": null,
      "perms": "refundapply:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 196,
      "parentId": 126,
      "parentName": "退差价复审",
      "name": "导出",
      "url": null,
      "perms": "refundapply:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 197,
      "parentId": 148,
      "parentName": "退差价三审",
      "name": "导出",
      "url": null,
      "perms": "refundapply:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 200,
      "parentId": 0,
      "parentName": null,
      "name": "报表查询",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 201,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "机构资金异动查询",
      "url": "modules/sys/dfmallSynthesisInfo.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 202,
      "parentId": 201,
      "parentName": "机构资金异动查询",
      "name": "查询",
      "url": null,
      "perms": "dfmallsynthesisinfo:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 203,
      "parentId": 201,
      "parentName": "机构资金异动查询",
      "name": "导出",
      "url": null,
      "perms": "dfmallsynthesisinfo:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 204,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "机构资金报表",
      "url": "modules/org/organizationFund.html",
      "perms": "",
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 205,
      "parentId": 204,
      "parentName": "机构资金报表",
      "name": "查询",
      "url": null,
      "perms": "organizationfund:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 206,
      "parentId": 204,
      "parentName": "机构资金报表",
      "name": "导出",
      "url": null,
      "perms": "organizationfund:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 207,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "订货分部奖励出金报表",
      "url": "modules/statements/dealerstatementreport.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 208,
      "parentId": 207,
      "parentName": "订货分部奖励出金报表",
      "name": "查看",
      "url": null,
      "perms": "report:statements:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 209,
      "parentId": 207,
      "parentName": "订货分部奖励出金报表",
      "name": "导出",
      "url": null,
      "perms": "report:statements:list:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 210,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "DF12出金报表",
      "url": "modules/statements/dealerstatement_d12report.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 211,
      "parentId": 210,
      "parentName": "DF12出金报表",
      "name": "查看",
      "url": null,
      "perms": "report:statementsd12:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 212,
      "parentId": 210,
      "parentName": "DF12出金报表",
      "name": "导出",
      "url": null,
      "perms": "report:statements12:list:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 213,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "过夜单统计查询",
      "url": "modules/org/acrossNightOrder.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 214,
      "parentId": 213,
      "parentName": "过夜单统计查询",
      "name": "查询",
      "url": null,
      "perms": "acrossnightorder:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 215,
      "parentId": 213,
      "parentName": "过夜单统计查询",
      "name": "导出",
      "url": null,
      "perms": "acrossnightorder:list:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 217,
      "parentId": 216,
      "parentName": "预付款优惠券管理",
      "name": "新增",
      "url": null,
      "perms": "coupon:detail:save",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 218,
      "parentId": 216,
      "parentName": "预付款优惠券管理",
      "name": "修改",
      "url": null,
      "perms": "coupon:detail:update,coupon:detail:info",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 219,
      "parentId": 216,
      "parentName": "预付款优惠券管理",
      "name": "删除",
      "url": null,
      "perms": "coupon:detail:delete",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 220,
      "parentId": 216,
      "parentName": "预付款优惠券管理",
      "name": "查询",
      "url": null,
      "perms": "coupon:detail:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 234,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "区域服务商资金查询",
      "url": "modules/servpro/dailyFund.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 236,
      "parentId": 200,
      "parentName": "报表查询",
      "name": "商城客户资金查询",
      "url": "modules/mallcustomer/customerCapitalQuery.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 238,
      "parentId": 0,
      "parentName": null,
      "name": "商城客户查询",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 239,
      "parentId": 238,
      "parentName": "商城客户查询",
      "name": "商城客户资金流水查询",
      "url": "modules/mallcustomer/customerCapital.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 240,
      "parentId": 238,
      "parentName": "商城客户查询",
      "name": "商城客户出入金查询",
      "url": "modules/mallcustomer/customerInOutMoney.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 241,
      "parentId": 238,
      "parentName": "商城客户查询",
      "name": "商城客户预订单查询",
      "url": "modules/mallcustomer/tradeHoldBill.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 242,
      "parentId": 238,
      "parentName": "商城客户查询",
      "name": "商城客户退订单查询",
      "url": "modules/mallcustomer/tradeCloseBill.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 243,
      "parentId": 238,
      "parentName": "商城客户查询",
      "name": "商城客户订单明细查询",
      "url": "modules/mallcustomer/tradeOrder.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 244,
      "parentId": 0,
      "parentName": null,
      "name": "区域服务商机构查询",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 245,
      "parentId": 244,
      "parentName": "区域服务商机构查询",
      "name": "区域服务商资金流水查询",
      "url": "modules/servpro/bmAmountlog.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 246,
      "parentId": 244,
      "parentName": "区域服务商机构查询",
      "name": "区域服务商出入金查询",
      "url": "modules/mallcustomer/providerOutMoney.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 247,
      "parentId": 241,
      "parentName": "商城客户预订单查询",
      "name": "查询",
      "url": null,
      "perms": "advanceOrder:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 248,
      "parentId": 241,
      "parentName": "商城客户预订单查询",
      "name": "导出",
      "url": null,
      "perms": "advanceOrder:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 249,
      "parentId": 242,
      "parentName": "商城客户退订单查询",
      "name": "查询",
      "url": null,
      "perms": "closeOrder:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 250,
      "parentId": 242,
      "parentName": "商城客户退订单查询",
      "name": "导出",
      "url": null,
      "perms": "closeOrder:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 251,
      "parentId": 243,
      "parentName": "商城客户订单明细查询",
      "name": "查询",
      "url": null,
      "perms": "orderDetail:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 252,
      "parentId": 243,
      "parentName": "商城客户订单明细查询",
      "name": "导出",
      "url": null,
      "perms": "orderDetail:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 253,
      "parentId": 245,
      "parentName": "区域服务商资金流水查询",
      "name": "查询",
      "url": null,
      "perms": "amountLog:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 254,
      "parentId": 245,
      "parentName": "区域服务商资金流水查询",
      "name": "导出",
      "url": null,
      "perms": "amountLog:download",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 255,
      "parentId": 234,
      "parentName": "区域服务商资金查询",
      "name": "查询",
      "url": null,
      "perms": "dailyFund:list",
      "type": 2,
      "icon": null,
      "orderNum": 0,
      "open": null,
      "list": null
    },
    {
      "menuId": 2,
      "parentId": 1,
      "parentName": "系统管理",
      "name": "管理员列表",
      "url": "modules/sys/user.html",
      "perms": "",
      "type": 1,
      "icon": "fa fa-user",
      "orderNum": 1,
      "open": null,
      "list": null
    },
    {
      "menuId": 33,
      "parentId": 0,
      "parentName": null,
      "name": "商城用户管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-users",
      "orderNum": 1,
      "open": null,
      "list": null
    },
    {
      "menuId": 34,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "等级申请表",
      "url": "modules/generator/syslevelapply.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-edit",
      "orderNum": 1,
      "open": null,
      "list": null
    },
    {
      "menuId": 292,
      "parentId": 0,
      "parentName": null,
      "name": "用户信息变更",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-edit",
      "orderNum": 1,
      "open": null,
      "list": null
    },
    {
      "menuId": 3,
      "parentId": 1,
      "parentName": "系统管理",
      "name": "角色管理",
      "url": "modules/sys/role.html",
      "perms": "",
      "type": 1,
      "icon": "fa fa-user-secret",
      "orderNum": 2,
      "open": null,
      "list": null
    },
    {
      "menuId": 31,
      "parentId": 0,
      "parentName": null,
      "name": "机构管理",
      "url": "modules/sys/bmorganization.html",
      "perms": "",
      "type": 0,
      "icon": "fa fa-institution",
      "orderNum": 2,
      "open": null,
      "list": null
    },
    {
      "menuId": 39,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "等级信息表",
      "url": "modules/generator/syslevelinfo.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-graduation-cap",
      "orderNum": 2,
      "open": null,
      "list": null
    },
    {
      "menuId": 295,
      "parentId": 0,
      "parentName": null,
      "name": "审批管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 2,
      "open": null,
      "list": null
    },
    {
      "menuId": 105,
      "parentId": 0,
      "parentName": null,
      "name": "订单管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "fa fa-sticky-note",
      "orderNum": 2,
      "open": null,
      "list": null
    },
    {
      "menuId": 4,
      "parentId": 1,
      "parentName": "系统管理",
      "name": "菜单管理",
      "url": "modules/sys/menu.html",
      "perms": "",
      "type": 1,
      "icon": "fa fa-th-list",
      "orderNum": 3,
      "open": null,
      "list": null
    },
    {
      "menuId": 44,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "商城用户表",
      "url": "modules/generator/dfmalluserinfo.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-vcard-o",
      "orderNum": 4,
      "open": null,
      "list": null
    },
    {
      "menuId": 101,
      "parentId": 105,
      "parentName": "订单管理",
      "name": "订单信息",
      "url": "modules/generator/orders.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 5,
      "open": null,
      "list": null
    },
    {
      "menuId": 149,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "转移机构管理",
      "url": "modules/org/shiftOrgVerify.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 5,
      "open": null,
      "list": null
    },
    {
      "menuId": 156,
      "parentId": 1,
      "parentName": "系统管理",
      "name": "定时任务",
      "url": "modules/job/schedule.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-tasks",
      "orderNum": 5,
      "open": null,
      "list": null
    },
    {
      "menuId": 182,
      "parentId": 97,
      "parentName": "风控图表",
      "name": "订货部备货金占用预测监控",
      "url": "modules/dataMonitor/capitalToAsset.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 5,
      "open": null,
      "list": null
    },
    {
      "menuId": 27,
      "parentId": 1,
      "parentName": "系统管理",
      "name": "参数管理",
      "url": "modules/sys/config.html",
      "perms": "sys:config:list,sys:config:info,sys:config:save,sys:config:update,sys:config:delete",
      "type": 1,
      "icon": "fa fa-sun-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 35,
      "parentId": 34,
      "parentName": "等级申请表",
      "name": "查看",
      "url": null,
      "perms": "syslevelapply:list,syslevelapply:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 36,
      "parentId": 34,
      "parentName": "等级申请表",
      "name": "新增",
      "url": null,
      "perms": "syslevelapply:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 37,
      "parentId": 34,
      "parentName": "等级申请表",
      "name": "修改",
      "url": null,
      "perms": "syslevelapply:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 38,
      "parentId": 34,
      "parentName": "等级申请表",
      "name": "删除",
      "url": null,
      "perms": "syslevelapply:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 40,
      "parentId": 39,
      "parentName": "等级信息表",
      "name": "查看",
      "url": null,
      "perms": "syslevelinfo:list,syslevelinfo:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 41,
      "parentId": 39,
      "parentName": "等级信息表",
      "name": "新增",
      "url": null,
      "perms": "syslevelinfo:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 42,
      "parentId": 39,
      "parentName": "等级信息表",
      "name": "修改",
      "url": null,
      "perms": "syslevelinfo:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 43,
      "parentId": 39,
      "parentName": "等级信息表",
      "name": "删除",
      "url": null,
      "perms": "syslevelinfo:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 45,
      "parentId": 44,
      "parentName": "商城用户表",
      "name": "查看",
      "url": null,
      "perms": "dfmalluserinfo:list,dfmalluserinfo:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 46,
      "parentId": 44,
      "parentName": "商城用户表",
      "name": "新增",
      "url": null,
      "perms": "dfmalluserinfo:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 47,
      "parentId": 44,
      "parentName": "商城用户表",
      "name": "修改",
      "url": null,
      "perms": "dfmalluserinfo:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 48,
      "parentId": 44,
      "parentName": "商城用户表",
      "name": "删除",
      "url": null,
      "perms": "dfmalluserinfo:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 53,
      "parentId": 49,
      "parentName": "工作日历",
      "name": "日历类型",
      "url": "modules/workday/openCloseType.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-list-alt ",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 54,
      "parentId": 53,
      "parentName": "日历类型",
      "name": "查看",
      "url": null,
      "perms": "openclosetype:list,openclosetype:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 55,
      "parentId": 53,
      "parentName": "日历类型",
      "name": "新增",
      "url": null,
      "perms": "openclosetype:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 56,
      "parentId": 53,
      "parentName": "日历类型",
      "name": "修改",
      "url": null,
      "perms": "openclosetype:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 57,
      "parentId": 53,
      "parentName": "日历类型",
      "name": "删除",
      "url": null,
      "perms": "openclosetype:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 58,
      "parentId": 49,
      "parentName": "工作日历",
      "name": "默认时间",
      "url": "modules/workday/openCloseConfig.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-calendar-check-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 59,
      "parentId": 58,
      "parentName": "默认时间",
      "name": "查看",
      "url": null,
      "perms": "openclosedefaultconfig:list,openclosedefaultconfig:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 61,
      "parentId": 58,
      "parentName": "默认时间",
      "name": "修改",
      "url": null,
      "perms": "openclosedefaultconfig:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 63,
      "parentId": 49,
      "parentName": "工作日历",
      "name": "特殊时间",
      "url": "modules/workday/openCloseSpecial.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-calendar-plus-o ",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 64,
      "parentId": 63,
      "parentName": "特殊时间",
      "name": "查看",
      "url": null,
      "perms": "openclosespecialconfig:list,openclosespecialconfig:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 65,
      "parentId": 63,
      "parentName": "特殊时间",
      "name": "新增",
      "url": null,
      "perms": "openclosespecialconfig:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 66,
      "parentId": 63,
      "parentName": "特殊时间",
      "name": "修改",
      "url": null,
      "perms": "openclosespecialconfig:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 67,
      "parentId": 63,
      "parentName": "特殊时间",
      "name": "删除",
      "url": null,
      "perms": "openclosespecialconfig:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 79,
      "parentId": 73,
      "parentName": "金贝管理",
      "name": "服务商金贝管理",
      "url": "modules/generator/dealerCount.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-gg-circle",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 80,
      "parentId": 79,
      "parentName": "服务商金贝管理",
      "name": "查看",
      "url": null,
      "perms": "dealerCount:list,dealerCount:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 81,
      "parentId": 79,
      "parentName": "服务商金贝管理",
      "name": "新增",
      "url": null,
      "perms": "dealerCount:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 82,
      "parentId": 79,
      "parentName": "服务商金贝管理",
      "name": "修改",
      "url": null,
      "perms": "dealerCount:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 83,
      "parentId": 79,
      "parentName": "服务商金贝管理",
      "name": "删除",
      "url": null,
      "perms": "dealerCount:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 84,
      "parentId": 73,
      "parentName": "金贝管理",
      "name": "机构金贝管理",
      "url": "modules/generator/orgCount.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-krw",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 85,
      "parentId": 84,
      "parentName": "机构金贝管理",
      "name": "查看",
      "url": null,
      "perms": "orgCount:list,orgCount:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 86,
      "parentId": 84,
      "parentName": "机构金贝管理",
      "name": "新增",
      "url": null,
      "perms": "orgCount:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 87,
      "parentId": 84,
      "parentName": "机构金贝管理",
      "name": "修改",
      "url": null,
      "perms": "orgCount:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 88,
      "parentId": 84,
      "parentName": "机构金贝管理",
      "name": "删除",
      "url": null,
      "perms": "orgCount:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 89,
      "parentId": 73,
      "parentName": "金贝管理",
      "name": "个人金贝管理",
      "url": "modules/generator/singleCount.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-money",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 90,
      "parentId": 89,
      "parentName": "个人金贝管理",
      "name": "查看",
      "url": null,
      "perms": "singleCount:list,singleCount:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 91,
      "parentId": 89,
      "parentName": "个人金贝管理",
      "name": "新增",
      "url": null,
      "perms": "singleCount:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 92,
      "parentId": 89,
      "parentName": "个人金贝管理",
      "name": "修改",
      "url": null,
      "perms": "singleCount:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 93,
      "parentId": 89,
      "parentName": "个人金贝管理",
      "name": "删除",
      "url": null,
      "perms": "singleCount:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 102,
      "parentId": 101,
      "parentName": "订单信息",
      "name": "查看",
      "url": null,
      "perms": "orders:list,orders:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 103,
      "parentId": 101,
      "parentName": "订单信息",
      "name": "新增",
      "url": null,
      "perms": "orders:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 104,
      "parentId": 101,
      "parentName": "订单信息",
      "name": "修改",
      "url": null,
      "perms": "orders:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 106,
      "parentId": 101,
      "parentName": "订单信息",
      "name": "删除",
      "url": null,
      "perms": "orders:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 107,
      "parentId": 105,
      "parentName": "订单管理",
      "name": "发货信息",
      "url": "modules/generator/deliveryapply.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 108,
      "parentId": 107,
      "parentName": "发货信息",
      "name": "查看",
      "url": null,
      "perms": "deliveryapply:list,deliveryapply:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 109,
      "parentId": 105,
      "parentName": "订单管理",
      "name": "回购信息",
      "url": "modules/generator/sellapply.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 110,
      "parentId": 109,
      "parentName": "回购信息",
      "name": "查看",
      "url": null,
      "perms": "sellapply:list,sellapply:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 111,
      "parentId": 109,
      "parentName": "回购信息",
      "name": "新增",
      "url": null,
      "perms": "sellapply:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 112,
      "parentId": 109,
      "parentName": "回购信息",
      "name": "修改",
      "url": null,
      "perms": "sellapply:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 113,
      "parentId": 109,
      "parentName": "回购信息",
      "name": "删除",
      "url": null,
      "perms": "sellapply:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 115,
      "parentId": 107,
      "parentName": "发货信息",
      "name": "新增",
      "url": null,
      "perms": "deliveryapply:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 116,
      "parentId": 107,
      "parentName": "发货信息",
      "name": "修改",
      "url": null,
      "perms": "deliveryapply:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 117,
      "parentId": 107,
      "parentName": "发货信息",
      "name": "删除",
      "url": null,
      "perms": "deliveryapply:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 118,
      "parentId": 119,
      "parentName": "商户信息",
      "name": "商户配置信息表",
      "url": "modules/delivery/merchant.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 120,
      "parentId": 125,
      "parentName": "退差价管理",
      "name": "退差价审核",
      "url": "modules/refundApply/refundapply.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 121,
      "parentId": 120,
      "parentName": "退差价审核",
      "name": "查看",
      "url": null,
      "perms": "refundapply:list,refundapply:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 122,
      "parentId": 120,
      "parentName": "退差价审核",
      "name": "新增",
      "url": null,
      "perms": "refundapply:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 123,
      "parentId": 120,
      "parentName": "退差价审核",
      "name": "修改",
      "url": null,
      "perms": "refundapply:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 124,
      "parentId": 120,
      "parentName": "退差价审核",
      "name": "删除",
      "url": null,
      "perms": "refundapply:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 126,
      "parentId": 125,
      "parentName": "退差价管理",
      "name": "退差价复审",
      "url": "modules/refundApply/refundRecheck.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 127,
      "parentId": 126,
      "parentName": "退差价复审",
      "name": "查看",
      "url": null,
      "perms": "refundapply:list,refundapply:info",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 128,
      "parentId": 126,
      "parentName": "退差价复审",
      "name": "新增",
      "url": null,
      "perms": "refundapply:save",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 129,
      "parentId": 126,
      "parentName": "退差价复审",
      "name": "修改",
      "url": null,
      "perms": "refundapply:update",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 130,
      "parentId": 126,
      "parentName": "退差价复审",
      "name": "删除",
      "url": null,
      "perms": "refundapply:delete",
      "type": 2,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 174,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "转移机构查询",
      "url": "modules/org/shiftOrgRecord.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 6,
      "open": null,
      "list": null
    },
    {
      "menuId": 29,
      "parentId": 1,
      "parentName": "系统管理",
      "name": "系统日志",
      "url": "modules/sys/log.html",
      "perms": "sys:log:list",
      "type": 1,
      "icon": "fa fa-file-text-o",
      "orderNum": 7,
      "open": null,
      "list": null
    },
    {
      "menuId": 148,
      "parentId": 125,
      "parentName": "退差价管理",
      "name": "退差价三审",
      "url": "modules/refundApply/refundThirdCheck.html",
      "perms": null,
      "type": 1,
      "icon": "fa fa-file-code-o",
      "orderNum": 7,
      "open": null,
      "list": null
    },
    {
      "menuId": 216,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "预付款优惠券管理",
      "url": "modules/coupons/coupondetail.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 7,
      "open": null,
      "list": null
    },
    {
      "menuId": 261,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "预付款券审核",
      "url": "modules/coupons/couponCheck.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 8,
      "open": null,
      "list": null
    },
    {
      "menuId": 271,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "券流水查询",
      "url": "modules/couponsReport/couponAmountlog.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 9,
      "open": null,
      "list": null
    },
    {
      "menuId": 274,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "券对账查询",
      "url": "modules/couponsReport/couponCompareAccount.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 10,
      "open": null,
      "list": null
    },
    {
      "menuId": 283,
      "parentId": 33,
      "parentName": "商城用户管理",
      "name": "券订单查询",
      "url": "modules/couponsReport/couponOrder.html",
      "perms": null,
      "type": 1,
      "icon": null,
      "orderNum": 11,
      "open": null,
      "list": null
    },
    {
      "menuId": 1,
      "parentId": 0,
      "parentName": null,
      "name": "系统管理",
      "url": "",
      "perms": "",
      "type": 0,
      "icon": "fa fa-cog",
      "orderNum": 99,
      "open": null,
      "list": null
    }
  ]
  
  export default data